development:
  adapter: postgresql
  encoding: utf8
  database: toodoo_development
  pool: 5
  username: lubson
  password: ratata

test: &test
  adapter: postgresql
  encoding: utf8
  database: toodoo_test
  pool: 5
  username: lubson
  password: ratat

production:
  adapter: postgresql
  encoding: utf8
  database: toodoo_production
  pool: 5
  username: lubson
  password: ratat

cucumber:
  <<: *test