development:
  adapter: postgresql
  encoding: utf8
  database: toodoo_development
  pool: 5
  username: mar1221
  password: 120586

test: &test
  adapter: postgresql
  encoding: utf8
  database: toodoo_test
  pool: 5
  username: mar1221
  password: 120586

production:
  adapter: postgresql
  encoding: utf8
  database: toodoo_production
  pool: 5
  username: mar120586
  password: 120586

cucumber:
  <<: *test